SIM = verilator
TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/../rtl/baud_gen.sv $(PWD)/../rtl/FIFO.sv $(PWD)/../rtl/UART_TX.sv $(PWD)/../rtl/UART_RX.sv $(PWD)/../rtl/UART.sv
TOPLEVEL = UART
MODULE = UART_test

include $(shell cocotb-config --makefiles)/Makefile.sim